// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yuvhwufnxukoikwkxvby.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl1dmh3dWZueHVrb2lrd2t4dmJ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEyODI2NjAsImV4cCI6MjA2Njg1ODY2MH0.FBhDFAVU-Du3BtWvGN2SuDsj4pCO0YvsAqtwQRGsijI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});